server:
  port: 8080
spring:
  application:
    name: quickstart

# 自定义配置，心情语录
my:
  # 心情语录
  mood:
    today: 周五
    content: 但是周六周日满课
    author: "卢本伟"
  #功能开关
  feature:
    helloSwitch: true
    closeMsg: "接口正在维护中,暂时关闭"

cs:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c4019917b3e5d21d29
      accountToken: 8d611cb958c241039cccd12fa79aab91
      appId: 2c94811c9860a9c4019917b3e7401d30
      templateId: 1